#!/usr/bin/env bash

CLEAN=0

for PARAM in $@; do
    case $PARAM in
	-c|--clean)
	    CLEAN=1
	    ;;
	-h|--help)
	    echo Help message
	    exit
	    ;;
    esac
done

PROJECT_ROOT=$(realpath $(dirname ${BASH_SOURCE[0]})/..)
MESON_BUILD_DIR=$PROJECT_ROOT/meson_build

# TODO Check init dependencies (bash, meson, git, coreutils, find)

if (( $CLEAN )); then
    find $PROJECT_ROOT -type l -name meson.build -delete
    exit
fi

pushd $MESON_BUILD_DIR > /dev/null
for MB in $(find . -name meson.build); do
    pushd $PROJECT_ROOT/$(dirname $MB) > /dev/null
    ln -sr $MESON_BUILD_DIR/$MB
    popd > /dev/null
done
popd > /dev/null
