def check_dependencies(ctx):
    raise NotImplementedError

def init_test_environment(ctx):
    raise NotImplementedError

def start_test_environment(ctx):
    raise NotImplementedError

def shutdown_test_environment(ctx):
    raise NotImplementedError

def clean_test_environment(ctx):
    raise NotImplementedError
