def check_dependencies(ctx):
    # TODO Надо проверить более строго
    ctx.cmd_and_log(["virsh", "-v"])

def init_test_environment(ctx):
    raise NotImplementedError

def start_test_environment(ctx):
    raise NotImplementedError

def shutdown_test_environment(ctx):
    raise NotImplementedError

def clean_test_environment(ctx):
    raise NotImplementedError
