#!/usr/bin/env bash

echo Hello!

# TODO Check python, coreutils and bash (maybe)

# FIXME check path arithmetic
PROJECT_ROOT=$(realpath "$(dirname ${BASH_SOURCE[0]})/..")
WAF_GIT_DIR=$PROJECT_ROOT/waf_build/waf_git
WAF_GIT_URL=TODO
WAF_GIT_BRANCH=master

FORCE=0
CLEAN=0

for PARAM in $@; do
    case $PARAM in
	-f|--force)
	    FORCE=1
	    ;;
	-c|--clean)
	    CLEAN=1
	    ;;
	-h|--help)
	    echo Help message
	    exit
	    ;;
    esac
done

SYMLINK_PLIST=TODO

echo Этот файл должен будет настраивать систему сборки для проекта
echo Проверить и поставить зависимости
echo Сделать симлинки для файлов системы сборки

# function check_symlink {
#     return [[ -h $1 ]]  # TODO
# }

# function set_symlink {
#     ln -s $1 $2  # TODO
# }

# function set_all_symlinks {
# }

# function delete_wscripts {
# }

# function clean {
# }

echo Если --force и --clean, то удалить waf и все симлинки
echo Если --clean то удалить симлинки
echo Если --force то пересоздать симлинки
echo Если без опций, то проверить наличие waf, если надо скачать и установить. Проверить симлинки, установить недостающие.

if [[ $FORCE && $CLEAN ]]; then
    echo Clean WAF
    # rm -rf "$WAF_GIT_DIR/*"
fi

if [[ $CLEAN || $FORCE ]]; then
    echo Clean symlinks
fi

pushd $WAF_GIT_DIR
if $(git status); then
    echo Download WAF
    # git init
    # git remote add -m $WAF_GIT_BRANCH -f origin $WAF_GIT_URL
    # TODO create symlinks to custom tools
fi
popd

# if $(check_symlinks); then
#     echo Create symlinks
# fi

echo Done
