import json
import SCons

class DevEnvNode(SCons.Node.Node):
    def __init__(self, dev_env_node):
        super().__init__()
        self.add_dependency(dev_env_node)
        self.filepath: str = str(dev_env_node)
        self.dev_env: dict = json.load(self.filepath)

    def __str__(self) -> str:
        return filepath

    def get_dev_env(self) -> dict:
        return self.dev_env

def create_pipenv(target, source, env):
    dev_env_dict = {}
    for s in source:
        dev_env_dict |= json.load(str(s))
    e = env.Copy(**dev_env_dict)
    e.Execute("pipenv update")

def create_dir_locals(target, source, env):
    raise NotImplementedError

dev_env_src = DevEnvNode(File("dev_env.json"))
pipfile_src = File("Pipfile")
venv_tgt = Dir(".venv")
dir_locals_tgt = File("#NaN/.dir_locals.el")
    
dev_pipenv = Command(venv_tgt, [dev_env_src, pipfile_src], create_pipenv)
dir_locals = Command(dir_locals_tgt, dev_env_src, create_dir_locals)
    
NoClean(dev_pipenv)
NoClean(dir_locals)
Alias("dev-config", [dev_pipenv, dir_locals])
